function [reg] = Regressionplots(SubjectName)
load(['.\' SubjectName '\' SubjectName '.mat'])
results_ei=eval([SubjectName '_ei']);
% results=eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);
% output=eval(['results.output_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);
% target=eval(['results.target_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);

% figure;
% plotregression(target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.train.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.train.indices'])),'Train',...
%     target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.validation.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.validation.indices'])),'Validation',...
%     target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.test.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.test.indices'])),'Test',...
%     target(1,:),output(1,:),'All')

figure;
plotregression(results_ei.target([1 2],results_ei.info.train.indices),...
    results_ei.output([1 2],results_ei.info.train.indices),'Train',...
    results_ei.target([1 2],results_ei.info.validation.indices),...
    results_ei.output([1 2],results_ei.info.validation.indices),'Validation',...
    results_ei.target([1 2],results_ei.info.test.indices),...
    results_ei.output([1 2],results_ei.info.test.indices),'Test',...
    results_ei.target([1 2],:),results_ei.output([1 2],:),[SubjectName ' All'])

% r=regression(results_ei.target([1 2],:),results_ei.output([1 2],:),'one');

reg=[results_ei.info.train.regression;
    results_ei.info.validation.regression; 
    results_ei.info.test.regression;
    regression(results_ei.target([1 2],:),results_ei.output([1 2],:),'one')];

% load(['./' SubjectName '/ANNmodel_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.mat']);
% results=eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);
% output=eval(['results.output_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);
% target=eval(['results.target_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange']);
% 
% figure;
% plotregression(target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.train.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.train.indices'])),'Train',...
%     target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.validation.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.validation.indices'])),'Validation',...
%     target(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.test.indices'])),...
%     output(1,eval(['results_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.info_IE_' SubjectName '_WS_8Hz_PhaseIncluded_SmRange.test.indices'])),'Test',...
%     target(1,:),output(1,:),'All')

end